CORPUS_ZH_PATH = "./corpus/corpus_zh.txt"
CORPUS_FR_PATH = "./corpus/corpus_fr.txt"
SENTENCE_ALIGN_PATH = "./corpus/sentence_align.txt"
TOKENISATION_PATH = "./corpus/tokenisation.txt"
WORD_ALIGN_PATH = "./corpus/word_align.txt"
IDIOM_ALIGN_PATH = "./corpus/idiom_align.txt"